### ISSUE TITLE
CordovA

### ISSUE THREAD

**Issue by lkscooby** [affilinet/mobile-sdk-publisher-ios#3]
Hi!

We have built a cross platform app in Cordova where we would be interested to  use your API.
Can we include  affilinet Mobile sdk publisher into a cordova project?

Thank You
Laszlo Barna

**Comment by avaffilinet** [comment]
Dear Laszlo,

you are warmly welcome to include the affilinet mobile SDK as a Publisher in any native iOS app you build, leveraging the product data API we provide. 

Since Cordova uses wrapped HTML/CSS to bridge platforms you have to deal with the fact that the affilinet SDK is made for native apps, executing web code in an invisible web view.

If it is an applicable scenario for you, we are delighted to see you using the affilinet mobile SDK.
Alternatively you might want to use our product data GET API directly embedded into your HTML/CSS/JS code: http://developer.affili.net/productdata-webservices/documentation/
